apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pod-config
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ toYaml .Values.podConfig | indent 4 }}
