apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secret
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ .Values.secrets.auth.htpasswd | b64enc }}
  signingKey: {{ .Values.secrets.http.signingKey | b64enc }}
