---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data-volume
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storageConfig.data.capacity }}
  accessModes: {{ .Values.storageConfig.data.accessModes }}
  hostPath:
    path: {{ .Values.storageConfig.data.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pv-claim
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.storageConfig.data.capacity }}
  volumeMode: Filesystem
  accessModes: {{ .Values.storageConfig.data.accessModes }}
