name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint using helm
        uses: WyriHaximus/github-action-helm3@v2.0
        with:
          exec: helm lint registry

  template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if templates are rendered
        uses: WyriHaximus/github-action-helm3@v2.0
        with:
          exec: helm template registry
